version: "3.8"

services:
  email-api:
    build: .
    container_name: email-api-service
    restart: unless-stopped

    # Exponha a porta interna (Coolify cuida do proxy externo)
    expose:
      - "3000"

    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME:-Email API Service}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      OFFER_URL: ${OFFER_URL}
      PRODUCT_NAME: ${PRODUCT_NAME}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-10}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-15}

    volumes:
      - ./leads:/app/leads
      - ./ebooks:/app/ebooks
      - ./templates:/app/templates

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

    networks:
      - email-api-network

networks:
  email-api-network:
    driver: bridge
    